### ISSUE TITLE
Endpoint that allows the user to check if an email is taken

### ISSUE THREAD

**Issue by Step7750** [MemePlace/Server#13]
This will allow us to have interactive validation when the user is typing in during sign up.

**Comment by Niustein** [comment]
I'll do this. I'd imagine this + community name are going to fairly identical code wise

**Comment by Step7750** [comment]
Yeah, it's just a distinct case insensitive check.

**Comment by Step7750** [comment]
@Niustein How's the progress on this issue?

**Comment by Niustein** [comment]
I started reading into form validation over the weekend and I believe I get it. Should be able to have it in a decent state by tomorrow.
