### ISSUE TITLE
Endpoint that allows the user to see if a community name is taken

### ISSUE THREAD

**Issue by Step7750** [MemePlace/Server#14]
Allow client side name validation as they type to ensure it is unique,

**Comment by xiningchen** [comment]
Mmm, I wouldn't mind doing this since I've already worked on the community form creation page... but I'm not sure where to start to connect our frontend with the server...

**Comment by Step7750** [comment]
Yeah, I'll make an issue for a APIDataService to handle the communication between the server and I'll finish it up tomorrow.

**Comment by Step7750** [comment]
Following restful stuff, I think the best URL for this would be:
`GET /api/v1/communities/:title/exists`

Which could just return a JSON response like `{exists: true}`

**Comment by xiningchen** [comment]
@Step7750 In your comment above, you said URL would be:
`GET /api/v1/communities/:title/exists`
Did you mean name instead of title? Just want to double check.

**Comment by Step7750** [comment]
Should be `GET /api/v1/communities/:name/exists` lol...

**Comment by xiningchen** [comment]
Hahahahaha, ok that's what I thought.
