### ISSUE TITLE
API Layout

### ISSUE THREAD

**Issue by Step7750** [MemePlace/Server#7]
### SF = Stepan's working on this

-----------------------------------------
API Layout Proposal:

DONE - POST /v1/auth - Authenticate user

DONE - POST /v1/users/ - Creates user
DONE (More attributes needed) - GET /v1/users/:user - Gets details about user
PUT /v1/users/:user - Updates user details (AUTH)

DONE - GET /v1/memes?sort=top|new&after=:memeid:&count=10 - Retrieves all memes sorted and paginated
DONE - GET /v1/memes/:memeid - Gets meme details
DONE - PUT /v1/memes/:memeid/vote - Vote for the meme (AUTH)
DONE - DELETE /v1/memes/:memeid/vote - Deletes vote for meme (AUTH)
DONE - DELETE /v1/memes/:memeid - Deletes the given meme (AUTH)
DONE - POST /v1/memes - Creates new meme (AUTH)

DONE - GET /v1/templates?sort=top|new&after=:memeid:&count=10 - Retrieves all templates sorted and paginated
DONE - GET /v1/templates/:templateid
DONE - DELETE /v1/templates/:templateid - Deletes the given template (AUTH)
DONE - POST /v1/templates - Creates new template (AUTH)

GET /v1/search/:text - Retrieves resources that match search text
DONE GET /v1/search/:text/autocomplete - Retrieves autocomplete search matches

DONE GET /v1/communities?sort=top|new|hot&offset=:offset:&count=10 - Retrieves all communities sorted and paginated
DONE - GET /v1/communities/:title - Retrieves details about the community
DONE - PUT /v1/communities/:title/favourite - Favourite community (AUTH)
DONE - DELETE /v1/communities/:title/favourite - Unfavourite community (AUTH)
DONE GET /v1/communities/:title/memes?sort=top|new|hot&after=:memeid:&count=10 - Retrieves memes from the community
DONE GET /v1/communities/:title/templates?sort=top|new|hot&after=:memeid:&count=10 - Retrieves templates used within the community

**Comment by xiningchen** [comment]
How can I help creating this? I'm not sure what's going on...

**Comment by Step7750** [comment]
I'll post up a PR in a little bit that fleshes it out.

**Comment by Step7750** [comment]
I believe all of these endpoints are completed
